== Hertz information from EDI airport versus Reality 

We queued for 1 1/2 hours at Hertz car rental and were forced to take this car otherwise we would get no other car even though we had a prepaid reservation

. Booked a fuel automatic "Kompaktklasse" (Kia Ceed or similar)
.. Hertz: Upgrade to a brand-new polestar 2; because no other car left
.. Reality: last car = no other option = take it or leave it = Downgrade !!! Size of the car doesn’t always mean upgrade. 

. Range of car
.. Claim by Hertz employee: At least 380 miles
.. reality: Max. 240 miles (at 100% charge which is not recommended by polestar)

. Age of car
.. Claim by Hertz employee: Brand-new
.. reality: Half year (9,339 miles on)

. State of car
.. Claim by Hertz employee: umdamaged
.. reality: We ignored, a big mistake, the scratches on the rims as many previous experiences from Ireland showed us that this is not an issue (even with Hertz bookings) -> Hertz now send an invoice for 2 new rims. 

. Charging
.. Claim by Hertz employee: Not a problem in Scotland, even in the highlands. Just use the shell fob or scan the QR code.  Car will be full within 15-30 minutes	
.. reality: We asked the employee 3 times if it is safe to go with an electric car into the highlands and were blatantly lied to with assurances that it’s “not a problem”. There is no shell station far and wide to use this given fob - therefore it’s useless to provide it. Web pay not working on most chargers ; many chargers broken and most chargers below 50kWh ; many even below 10kWh. SLOW chargers !  Charging for hours per day at locations far away from interesting anything because you have to take the working charger you can find (if you can find it). Only RFID cards working on many of the chargers. Hertz didn’t provide a chargescotland card that maybe would have helped at least a tiny bit. Driving around from one broken/non-useable charger to the next instead of enjoying Scotland, the highlands and visiting attractions. Because you need the battery to be filled up to get anywhere! It is impossible to tell from the map if the charger supports web pay even if it was recently used.  Spending money (40 GBP) for a ferry to get to a charging point on the Isle of Mull port that was broken too and not visiting anything because we had to get back on the next ferry to try to reach a slow charger with remaining battery level. Lots of calls with mobile phone to get to an operator to clarify situation at charging stations or to make them available through restart etc ; using up mobile data for loading websites; we had to re-arrange the planned route to match the vehicle conditions and had to re-arrange accommodations.  We missed most of our planned attractions to visit.  Charging car on household over night for max +35 % battery charging to get 84 miles (35% of 240 miles = 84 miles; instead of 35% of told 380 miles =  126 miles)

. Customer service at Hertz
.. Giving us a number on the contract that you can contact. The number is an automated loop that leads either back on itself or to a hang up unless reservation is selected. There is no service from hertz.  You are told to ring the number you just rang and then the automatic system hangs up. No calls returned even if we asked multiple times for them. Over the hotline for reservations because that’s the only line working in the menu. Assuerd by the reservations people that will pass the information on to the station to return a call. Zero calls returned. Web chat leads to: “call roadside assistance”. Zero service and zero help. You leave your customers sitting in trouble and don’t care !   Incompetency in giving information about opening hours for returning the car at Holyhead Port on Monday (28th Aug) - Both station and compound closed. Spending nearly an hour to get everything arranged to get rid of that car to reach our ferry. At least two other poeple tried to return cars during that time and stood confronted with similar issues.
. Charge for returning to other site
.. Claim by Hertz employee: 800 GBP; better to use train, bus or plane = good advice ???   	
.. reality: 166.67 GBP (as reservation employee told us after we called Hertz again to arrange a reservation for EDI airport or Glasgow airport on Sunday to get another car that can be returned in Holyhead;  As both stations were closed on Sunday we had to drive the Polestar to Holyhead; due to no call back from Hertz and arranging a compromise with customer we had no chance to return the Polestar to EDI airport or Glasgow airport .  Threatened by Hertz EDI airport “You will return vehicle here or else you will be charged 800 GBP”

. Return car at Holyhead port
.. reality: All 4 places full ; office closed; no answer on phone on sign@station ; alternative Hertz compound locked, had to call harbour master to add license plate to white list to avoid towing: most chargers @port nonfunctional; only working one had to be remotely restarted

. Additional driver for free (as offered in booking)
.. reality: Charged for and said we have to claim it back from the broker as it is not an Hertz offering 	

== Chargers

. Fort William
.. Arrived on first day and parked at unoccupied charger of 3. Made multiple attempts with car connected first or last etc. before ringing charge place scottland to be told it doesn't work with web pay and to try one of the others. Both 50kw chargers taken so hooked up to AC and then later moved to one of the 50kw as it was freed up. As AC was slow, the ferry was out, and we had to make the accomodation before night we stopped charging on DC when we had enough to get us to the next charger the next day. Still hours wasted in a parking space between two supermarkets. Only saving grace was that we could buy food for a picknick as there was no longer any way to eat out as planned. Arrived very late at our accomodation.

. Port Kilchoan
.. Charger nonfunctional, no web pay, just errors. Told by a chargescotland employee to go to Tobermory. 38 GBP, return, for the ferry. 

. Tobermory. 
.. Charger broken, no web pay. No time on the Isle of Mull as next charger is slow. Family stress. 
 
. Ardnamurchan Lighthouse
.. Cafe closed as we arrived. Slow charger, promised 20KW, gave 7.4. 1 1/4 hours to recharge enough to get back, 3% battery left on return to accomodation after a day of searching for working chargers.

. Oban
.. Chargers near the distillery, no web payment. Charger at the port gave grief but a fellow EV driver lent a hand, stating owning an electric car in Scotland was madness. He let us in on his card, saying tourists shouldn't endure an EV here. Charged AC first then later DC when that finaly turned green.

. Dunoon
.. A charger at the pier blocked by rides. The supermarket charger, inert (Genie Point).

. Lancaster
.. The first Shell station with an EV charger on the route. 39 kWh instead of 50. Brand new, but not working properly so dialed down.

. Colwyn Bay
.. Charger at the pier, "bppulse." App-only activation via app in the UK store only. A helpful bppulse employee activated it, no charge. Charged over night, returned early to queue of 2 waiting cars.

. Holyhead
.. At Holyhead, we heard it plain and simple from a harbor worker: "You're lucky, all the rest don't work." A 5 GBP parking fee for 20 minutes in a designated charging spot. The system needed a remote reboot before working. Over 20 minutes on the phone with the operator just to get it started. It was easier to pay the parking online.

. Diverse Broken Chargers
.. Broken chargers everywhere. Lights, no lights, car refuses, activation won't work. Endless experiments, lost time and wasted charge.


== Conclusion
Vacation in Scotland:: Had none; only trouble and a row of bad experiences; more costs caused by third parties; absolutely disappointing ; not to recommend; spending valuable vacation time spent hunting charge points and making calls and now writing Emails.
		
== Images from the trenches
