name: asciidoc pdf and html
on:
  push:
    paths:
      - '**.adoc'
      - '**.asciidoc'
      - '.github/workflows/adoc.yml'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make the PDFs and HTMLs
        id: asciidoc-2-html-and-pdf
        run: |
          docker pull ghcr.io/donnels/asciidoc:main
          docker run -v "$PWD":/documents/ --name asciidoc-to-pdf ghcr.io/donnels/asciidoc:main asciidoctor-pdf -D /documents/docs *.asciidoc
          docker run -v "$PWD":/documents/ --name asciidoc-to-html ghcr.io/donnels/asciidoc:main asciidoctor -D /documents/docs *.asciidoc

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
